/**
 * Export utilities — generates downloadable files (CSV/Excel and PDF placeholder).
 */

export function exportAsCSV(data: Record<string, unknown>[], filename: string) {
  if (data.length === 0) return

  const headers = Object.keys(data[0])
  const csvRows = [
    headers.join(','),
    ...data.map((row) =>
      headers
        .map((h) => {
          const val = String(row[h] ?? '')
          return val.includes(',') ? `"${val}"` : val
        })
        .join(','),
    ),
  ]

  const blob = new Blob([csvRows.join('\n')], { type: 'text/csv' })
  downloadBlob(blob, `${filename}.csv`)
}

export function exportAsPDF(title: string, content: string) {
  // Placeholder — in production use jsPDF or backend PDF generation
  const pdfContent = `COMPANY NAME\n${title}\n${'='.repeat(40)}\n\n${content}\n\nGenerated by Payroll System`
  const blob = new Blob([pdfContent], { type: 'text/plain' })
  downloadBlob(blob, `${title.replace(/\s+/g, '_')}.txt`)
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

/**
 * Show export format picker and trigger download.
 */
export function triggerExport(title: string, data: Record<string, unknown>[]) {
  const format = window.prompt('Export format:\n\n1 - Excel (CSV)\n2 - PDF\n\nEnter 1 or 2:', '1')

  if (format === '1') {
    exportAsCSV(data, title)
  } else if (format === '2') {
    const content = data.map((row) => Object.entries(row).map(([k, v]) => `${k}: ${v}`).join(' | ')).join('\n')
    exportAsPDF(title, content)
  }
}
